server:
  port: 2023

Person:
  last-name: John${random.uuid}
  age: ${random.int}
  happy: true
  birth: 2020/11/11
  maps: {k1: v1,k2: v2}
  lists:
    - code
    - music
    - girls
  dog:
    name: ${person.hello:hello}
    age: 3
dog:
  first-name: 阿黄
  age: 3
#关闭默认图标

